### ISSUE TITLE
Potential data availability issue

### ISSUE THREAD

**Issue by Gennadiyev** [Yixuan423/FakeBench#2]
Thank you for providing access to the FakeBench data, the work is insightful. Unfortunately, it seems that the data hosted on OneDrive cannot be fully downloaded from mainland China, even when using a VPN. Would it be possible to upload the FakeBench data to an alternative platform, preferably Google Drive? This would greatly help users facing similar issues.

Thank you for your consideration!

**Comment by Yixuanli423** [comment]
Thanks for your kind reminder. We will change the data source in no time.

**Comment by Yixuanli423** [comment]
> Thank you for providing access to the FakeBench data, the work is insightful. Unfortunately, it seems that the data hosted on OneDrive cannot be fully downloaded from mainland China, even when using a VPN. Would it be possible to upload the FakeBench data to an alternative platform, preferably Google Drive? This would greatly help users facing similar issues.
> 
> Thank you for your consideration!

Fixed.
